### PR TITLE
US-1/ Login functionality verification tests are added

### PR DESCRIPTION
**Pull request by olek-pas**
Created test cases for valid/invalid login functionality verification

### CODE REVIEW

**Review by leodubois14 — APPROVED** [review]
checked your code--> all test cases passed

**Review by Serkanbjk — APPROVED** [review]

**Review by ALik042 — APPROVED** [review]

**Review by ozangillum — APPROVED** [review]
Looks good to me to merge.

**Comment by aydinmhrrm** [comment]
Good Job!

**Comment by MadinaRam** [comment]
Looks very nice!

**Review by oshesternyak — COMMENTED** [review]
Looks good!

**Pull request merged**
